name:  Solar_system CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
         - name: Checkout code
           uses: actions/checkout@v2  
           
         - name:  install Node.js
           uses: actions/setup-node@v2
           with:
             node-version: '16'

         - name: Install dependencies
           run: npm install

         - name: Audit Fix For Dependices 
           run: npm audit fix

         - name : Found the Updated Package Details 
           run: npm fund

         - name: Adding the Secrtes in Git Secrets 
           echo: Added the Mongo Secrets as in Git secrets 

         - name: Run tests
           env:
            MONGO_URI: ${{ secrets.MONGO_URI }}
            MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
            MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
           run: npm test
        
        
   

